### ISSUE TITLE
Import Error with python_hosts 0.4.6

### ISSUE THREAD

**Issue by jonnyyu** [jonhadfield/hostman#1]
>>> import hostman
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/DATA/ci/amac/client_tools/venv/lib/python2.7/site-packages/hostman/__init__.py", line 30, in <module>
    from python_hosts import Hosts, HostsEntry
ImportError: cannot import name Hosts

**Comment by jonhadfield** [comment]
Oops. Should now be fixed.
